server:
  port: 8083
  servlet:
    context-path: /api/order

spring:
  profiles:
    active: db,eurekaclient,feign,security,zipkin
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order?createDatabaseIfNotExist=true

springdoc:
  packagesToScan: com.norberttalpos.order