server:
  port: 8084
  servlet:
    context-path: /api/customer

spring:
  profiles:
    active: db,eurekaclient,feign,security
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer?createDatabaseIfNotExist=true

springdoc:
  packagesToScan: com.norberttalpos.customer