package com.norberttalpos.auth.core.model.entity

import com.norberttalpos.common.abstracts.entity.AbstractAutoGeneratedIdEntity
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.Table


@Entity(name = "Role")
@Table(name = "role")
class Role : AbstractAutoGeneratedIdEntity() {

    @Column(nullable = false, unique = true)
    var name: String? = null
}