server:
  port: 8080

spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/product?createDatabaseIfNotExist=true
    username: norberttalpos
    password: Passw0rd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    generate-ddl: true