package com.norberttalpos.product.core.entity

import com.norberttalpos.common.abstracts.entity.AbstractAutoGeneratedIdEntity
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.Table

@Entity(name = "MeasurementUnit")
@Table(name = "measurement_unit")
class MeasurementUnit : AbstractAutoGeneratedIdEntity() {

    @Column(name = "name", nullable = false, updatable = false, unique = true)
    var name: String = ""
}