package com.norberttalpos.product.core.entity

import com.norberttalpos.common.abstracts.entity.AbstractAutoGeneratedIdEntity
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.OneToMany
import javax.persistence.Table

@Entity(name = "ProductCategory")
@Table(name = "product_category")
class ProductCategory : AbstractAutoGeneratedIdEntity() {

    @Column(name = "name", nullable = false, unique = true)
    var name: String = ""

    @Column(name = "parent")
    var parent: Int = 0

    @OneToMany(mappedBy = "category")
    var products: List<Product>? = emptyList()
}