package com.norberttalpos.product.core.entity

import com.norberttalpos.common.abstracts.entity.AbstractAutoGeneratedIdEntity
import javax.persistence.*

@Entity(name = "ProductBrand")
@Table(name = "product_brand")
class ProductBrand : AbstractAutoGeneratedIdEntity() {
    @Column(name = "name", nullable = false, unique = true)
    var name: String = ""

    @Column(name = "country", nullable = false)
    var country: String = ""

    @OneToMany(mappedBy = "brand", cascade = [CascadeType.ALL])
    var products: List<Product>? = emptyList()
}