package com.norberttalpos.product.core.entity

import com.norberttalpos.common.abstracts.entity.AbstractAutoGeneratedIdEntity
import javax.persistence.*

@Entity(name = "ProductCategory")
@Table(name = "product_category")
class ProductCategory : AbstractAutoGeneratedIdEntity() {

    @Column(name = "name", nullable = false, unique = true)
    var name: String = ""

    @Column(name = "parent")
    var parent: Int = 0

    @OneToMany(mappedBy = "category", cascade = [CascadeType.ALL])
    var products: List<Product>? = emptyList()
}