services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: norberttalpos
      POSTGRES_PASSWORD: Passw0rd
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: norberttalpos
      KEYCLOAK_PASSWORD: Passw0rd
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: norberttalpos
      DB_PASSWORD: Passw0rd
    ports:
      - "9000:8080"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: