server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/product/**

        - id: product-brand
          uri: lb://product-service
          predicates:
            - Path=/api/product-brand/**

        - id: product-category
          uri: lb://product-service
          predicates:
            - Path=/api/product-category/**

        - id: measurement-unit
          uri: lb://product-service
          predicates:
            - Path=/api/measurement-unit/**

        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost