server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/$\{path}/v3/api-docs

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9000/auth/realms/baguette
        registration:
          keycloak-api-gateway-client:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: qfcF7tPvTUSo2PmN8esPzEFErMlDKqDT
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

springdoc:
  swagger-ui:
    urls:
      - name: product
        url: /v3/api-docs/product
      - name: cart
        url: /v3/api-docs/cart

logging:
  level:
    org:
      springframework:
        security: DEBUG