server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/$\{path}/v3/api-docs

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customer/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

springdoc:
  swagger-ui:
    urls:
      - name: product
        url: /v3/api-docs/product
      - name: cart
        url: /v3/api-docs/cart
      - name: customer
        url: /v3/api-docs/customer
      - name: order
        url: /v3/api-docs/order
      - name: auth
        url: /v3/api-docs/auth

logging:
  level:
    org:
      springframework:
        security: DEBUG