server:
  port: 8081
  servlet:
    context-path: /api/cart

spring:
  profiles:
    active: db,eurekaclient,feign,security,zipkin
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cart?createDatabaseIfNotExist=true

springdoc:
  packagesToScan: com.norberttalpos.cart