package com.norberttalpos.order.core.entity

import com.norberttalpos.common.abstracts.entity.AbstractAutoGeneratedIdEntity
import com.norberttalpos.order.api.dto.OrderStatus
import java.util.*
import javax.persistence.*

@Entity(name = "Order")
@Table(
    name = "order_table",
    uniqueConstraints = [UniqueConstraint(columnNames = ["cart_id", "customer_id"])]
)
class Order : AbstractAutoGeneratedIdEntity() {

    @Column(name = "cart_id", nullable = false)
    var cartId: UUID? = null

    @Column(name = "customer_id", nullable = false)
    var customerId: UUID? = null

    @Enumerated(EnumType.STRING)
    var status: OrderStatus = OrderStatus.ordered
}