package com.norberttalpos.order.core.entity

import com.norberttalpos.common.abstracts.entity.AbstractAutoGeneratedIdEntity
import java.util.*
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.Table
import javax.persistence.UniqueConstraint

@Entity(name = "Order")
@Table(
    name = "order",
    uniqueConstraints = [UniqueConstraint(columnNames = ["cart_id", "customer_id"])]
)
class Order : AbstractAutoGeneratedIdEntity() {

    @Column(name = "cart_id", nullable = false)
    var cartId: UUID? = null

    @Column(name = "customer_id", nullable = false)
    var customerId: UUID? = null
}